-- 1) 作业运行记录（最小上帝视角）
CREATE TABLE IF NOT EXISTS PROGRAM.ETL_JOB_RUN (
    JOB_ID VARCHAR(50) PRIMARY KEY,
    START_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    END_TIME TIMESTAMP,
    STATUS VARCHAR(20),
    TOTAL_FILES INT DEFAULT 0,
    SUCCESS_FILES INT DEFAULT 0,
    FAILED_FILES INT DEFAULT 0
);

-- 2) 文件幂等日志
CREATE TABLE IF NOT EXISTS PROGRAM.ETL_FILE_LOG (
    FILE_SHA1 VARCHAR(64) PRIMARY KEY,
    FILE_NAME VARCHAR(255),
    BIZ_TYPE VARCHAR(50),
    STATUS VARCHAR(20),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3) 页任务追踪 (修正了达梦自增方言 IDENTITY)
CREATE TABLE IF NOT EXISTS PROGRAM.ETL_PAGE_TASK (
    ID BIGINT IDENTITY(1, 1) PRIMARY KEY,
    JOB_ID VARCHAR(50),
    FILE_SHA1 VARCHAR(64),
    PAGE_NO INT,
    PAGE_TYPE VARCHAR(20),
    STATUS VARCHAR(20),
    REASON_CODE VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4) 页级抽取结果留痕
CREATE TABLE IF NOT EXISTS PROGRAM.ETL_EXTRACT_RESULT (
    ID BIGINT IDENTITY(1, 1) PRIMARY KEY,
    FILE_SHA1 VARCHAR(64),
    PAGE_NO INT,
    RAW_JSON CLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5) 死信队列表
CREATE TABLE IF NOT EXISTS PROGRAM.ETL_DLQ (
    ID BIGINT IDENTITY(1, 1) PRIMARY KEY,
    FILE_NAME VARCHAR(255),
    PAGE_NO INT,
    ERROR_REASON VARCHAR(500),
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6) 参数表去重字段与唯一索引
-- 如果字段已存在，脚本会容错跳过
ALTER TABLE PROGRAM.PA_CRANE_PARAMETERS ADD COLUMN PARAM_FINGERPRINT VARCHAR(64);
COMMENT ON COLUMN PROGRAM.PA_CRANE_PARAMETERS.PARAM_FINGERPRINT IS '参数行级去重指纹(SHA1)';

-- 建议在历史数据清洗完成后，再执行唯一索引创建（推荐运行 scripts/enforce_unique_indexes.py）：
CREATE UNIQUE INDEX IDX_CRANE_PARAM_FP
ON PROGRAM.PA_CRANE_PARAMETERS (DEVICE_ID, PARAM_FINGERPRINT);

CREATE UNIQUE INDEX IDX_SYS_FILE_DEDUP
ON PROGRAM.SYS_BASE_FILE (BIZ_ID, FILE_NAME, ORDER_TYPE);